Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
